# -*- coding: utf-8 -*-
"""TimeTableGenerator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kX8DL5xROPk-Il4kI4jhWss1odoXa1-n
"""

import pandas as pd
import random

print("TIMETABLE GENERATOr\n")

# user Inputs
subjects_input = input("Enter subjects (comma separated):")
days_input = input("Enter days (coma separated):")
periods_per_day = int(input("Enter number of periods per day:"))

# process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input. Please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)

  # Create DataFrame
  df = pd.DataFrame(timetable)
  df,index = [f"Period {i+1}" for i in range(periods_per_day)]

  print("\nTimetable Generated Successfully\n")
  display(df)

  # Save timetable
  df.to_csv("timetable.csv")
  print("\nTimetable saved as timeable.csv")